name: tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46

      - name: Run tests
        run: go test -v $(go list ./... | grep -v vendor)
